// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function DeleteAudio(arg1) {
  return window['go']['main']['App']['DeleteAudio'](arg1);
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetAudios() {
  return window['go']['main']['App']['GetAudios']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function ImportAudioFile() {
  return window['go']['main']['App']['ImportAudioFile']();
}

export function ImportAudioFiles(arg1) {
  return window['go']['main']['App']['ImportAudioFiles'](arg1);
}

export function Minimise() {
  return window['go']['main']['App']['Minimise']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PlayAudioID(arg1) {
  return window['go']['main']['App']['PlayAudioID'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResetAudio() {
  return window['go']['main']['App']['ResetAudio']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function SaveSidebarState(arg1) {
  return window['go']['main']['App']['SaveSidebarState'](arg1);
}

export function SaveWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SaveWindowSize'](arg1, arg2);
}

export function SetAudioSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAudioSettings'](arg1, arg2, arg3);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function StartUpdate(arg1) {
  return window['go']['main']['App']['StartUpdate'](arg1);
}

export function ToggleMaximise() {
  return window['go']['main']['App']['ToggleMaximise']();
}

export function UpdateAudioOrder(arg1) {
  return window['go']['main']['App']['UpdateAudioOrder'](arg1);
}

export function UpdateHotkey(arg1, arg2) {
  return window['go']['main']['App']['UpdateHotkey'](arg1, arg2);
}
