// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.CheckUpdateResult>;

export function DeleteAudio(arg1:string):Promise<void>;

export function GetAudioDevices():Promise<Array<main.AudioDevice>>;

export function GetAudios():Promise<Array<main.AudioItem>>;

export function GetConfig():Promise<main.Config>;

export function Hide():Promise<void>;

export function ImportAudioFile():Promise<string>;

export function ImportAudioFiles(arg1:Array<string>):Promise<string>;

export function Minimise():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PlayAudioID(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function ResetAudio():Promise<void>;

export function SaveSettings(arg1:string,arg2:boolean):Promise<void>;

export function SaveSidebarState(arg1:boolean):Promise<void>;

export function SaveWindowSize(arg1:number,arg2:number):Promise<void>;

export function SetAudioSettings(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Show():Promise<void>;

export function StartUpdate(arg1:string):Promise<void>;

export function ToggleMaximise():Promise<void>;

export function UpdateAudioOrder(arg1:Array<string>):Promise<void>;

export function UpdateHotkey(arg1:string,arg2:string):Promise<void>;
